import Link from 'next/link'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const links = [
  { href: '/', label: 'Home' },
  { href: '/specs', label: 'Spec Sheet' },
  { href: '/invoice', label: 'Generate Invoice' },
  { href: '/inventory', label: 'Manage Inventory' }
]


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
  
  const links = [
  { href: '/', label: 'Home' },
  { href: '/specs', label: 'Spec Sheet' },
  { href: '/invoice', label: 'Generate Invoice' },
  { href: '/inventory', label: 'Manage Inventory' }
]
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <ul className="flex items-center">
              {links.map((link) => (
                <li key={link.href}>
                  <Link href={link.href}>{link.label}</Link>
                </li>
              ))}
            </ul>
          </nav>
        </header>
        <div>{children}</div>
      </body>
    </html>
  )
}
